### PR TITLE
Update packages and fix deprecation messages

### PR DESCRIPTION
**Pull request by toburger**
After updating the packages from my own project I got deprecation messages from suave-appinsights.fs when building my project.

I have updated this project to the latest packages and tried to resolve the deprecation messages.
I'm not sure if deleting the second argument for ExceptionTelemetry is the right thing to do, but I have trouble to find adequate documentation for AI.

### CODE REVIEW

**Comment by isaacabraham** [comment]
On holiday for next week - will review properly when I'm back - any reason why we now depend on Core 4.1 (are there any problems doing that?) and why the lock file is now like a million times bigger? :)

**Comment by isaacabraham** [comment]
But thank you for updating this - AI works quite currently now with the latest API so this does need doing- thank you for starting this off.

**Comment by toburger** [comment]
Sorry, didn't notice the change in size... The framework restriction should do the trick!
Yeah, AI works fine, but the compiler warnings bugs me every time I build my project. ;)

**Comment by toburger** [comment]
AI has now removed the deprecated functionality in the latest 2.3 release.

**Comment by toburger** [comment]
Forget what I've said before: the deprecated methods aren't removed, but AI has now added a new overload for the StartOperation method, so the first argument cannot be inferred automatically.
The master branch doesn't compile anymore, my pull requests compiles though...

**Comment by toburger** [comment]
Ok, there was more to do than that:
* AI 2.3 adds the new overload, like said above
* Suave 2.1 now depends on .NET Framework 4.6, so I had to update the solution to .NET 4.6.

Another possibility is to lock Suave to 2.0, but I think it is better to be on par with the latest release of Suave.

**Comment by toburger** [comment]
Any chance to merge this pull request?
I'm using my branch in production since April and didn't encounter any problem.

**Comment by isaacabraham** [comment]
I'm terribly sorry for not having dealt with this sooner. Thanks For doing this - really appreciated.

**Comment by toburger** [comment]
No problem, thx for merging!

**Pull request merged**
